version: '3.7'

services:
  media-catalog-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/app/src
    container_name: media-catalog-service
    expose:
      - '4001'
    ports:
      - '4001:4001'
